### ISSUE TITLE
Different/More stuff to game/shop? SUGGESTION

### ISSUE THREAD

**Issue by matt729** [Steffion/BlockHunt#219]
Hey! I was wondering if you will ever add more things to the shop.
Ideas mentioned in #89 are good in my opinion too, but you guys haven’t seemed to add them :(.

(SHOP) Firstly, In the code of the plugin (I’m a basic coder), I think it says that there is someway to make people buy the book to choose your block, can you add that, instead of just the very beginners be able to choose their block? (EDIT*, I was checking some things out, and did you add this? If so, I don't seem to have it.)

(SHOP) Secondly, THESE ARE FROM #89, but I like them very much, be able to instant hide with an item, maybe sugar, that when you right click makes you become solid right away(don’t take that the wrong way...), AND something that if you right click on a block that is on the block chooser list (while in a game of course), become it.

Thirdly, the new things:
1. (GENERAL IDEA) Be able to disguise as animals, and animals restart with the map! (not an original idea)
2. (SHOP) Lobby time down, makes the lobby time cut in half, 1 time use
3.  (SHOP) Super speed, right click an item, and you will get speed III for 10 secs to run away from the seekers! 1 time use,
4. (SHOP) Hider Weapon upgrade, makes hiders get a stone sword with knockback  II, unlimited uses, 
5. (GENERAL IDEA) Hider Snowballs, make hiders get 10 snowballs, or eggs, to use in dangerous situations.
6. (HARD to do GENERAL IDEA) For bigger servers, have an OPTION that instead of just having maps that the player can join, have a server/world the player can join in. While in the players can vote on the arena they want to play in, and whatever arena gets the most votes, they play, but if you do decide to do this, make it only an option. 

Thanks for reading this, and I hope some of these may get added in the next update!

**Comment by Steffion** [comment]
If you still would like to see your new features and all, make a new issue PER idea. This is easier for us.
I will close this one for now and feel free to create new ones.
