### ISSUE TITLE
+ 2 New features to the plugin and a bug

### ISSUE THREAD

**Issue by NonameSL** [Steffion/BlockHunt#241]
(Instead of bugging you guys with 3 new issues I just crammed all of my ideas here)

1. I would really like a command that force joins or force leaves like 
/bh forcejoin <playername> <arenaname> or
/bh forceleave <playername> <arenaname>.

2. Another option that can be cool is an option to force join ALL players online to an arena, like
/bh joinall <arenaname>

(Possible) BUG:
3. When a player joins an arena then leaves it, he is teleported to the lobby. Why isn't the player teleported to where he joined the arena? If this isn't a bug, I would really like this option to be added to the game.

**Comment by Steffion** [comment]
If you still would like to see your new features and all, make a new issue PER idea. This is easier for us.
I will close this one for now and feel free to create new ones.
