### ISSUE TITLE
Block Glitching

### ISSUE THREAD

**Issue by RainbowRods** [Steffion/BlockHunt#296]
Not so much plugin related, but it'd be nice if people couldn't break blocks (aka Adventure mode). If you could make it so they're in adventure mode I think that'd be good!

**Comment by coolnickname** [comment]
i read the source, players can't break/place blocks unless it is an sign and the player has the permission for that.

**Comment by Steffion** [comment]
Most likely another plugin is interfering with it. The plugin should be cancelling any block breaking event.

I can not change it to adventure mode because the seekers wouldn't be able to hit the 'solid' hiders blocks.
