### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by orangeghast** [Steffion/BlockHunt#297]
Hi.
It would be great if you could make a thing in the config called 'BUNGEE' : true/false
Also a thing that says 'HUB SERVER: <the server to disconnect to>'
And finally 'GAME: <game that players automatically get connected to>

When bungee is set to true, when players join the server, they automatically join the set games.
When the games ends, they automatically are disconnected to the hub server with Bungee Cord.
Also when the game is in lobby, it sets the server MOTD to 'Lobby' and when the game is going it sets it to 'In-Game'.

And also it wouldn't be bad if it makes it so when people try and join while the game is going it redirects them to the lobby

**Comment by Steffion** [comment]
For now I will not add support for bungee.
