### ISSUE TITLE
NullPointerExeption ChestCommands GUI and BlockHunt

### ISSUE THREAD

**Issue by MinecrafterTim12** [Steffion/BlockHunt#313]
Hello,
i have a problem with my server.
i use a inventory GUI plugin as a teleporter.
however everytime i klick on a item in the GUI this NullpoinerExeption will print in the console

Pastebin URL: http://pastebin.com/cNJK1T01

Thx MinecrafterTim12

P.S. Sorry for my englisch iam german

**Comment by Steffion** [comment]
I believe this was fixed with #122 
If you still have problems, please leave a message.
