### ISSUE TITLE
Support for Spigot 1.8

### ISSUE THREAD

**Issue by drew5494** [Steffion/BlockHunt#320]
This plugin has lagged my entire server to the point where players are unable to move.  Please update this great plugin.

**Comment by eglbogle** [comment]
We need Block Hunt for the latest version of Spigot. I've tried using the latest version of Block Hunt, and it lags the server horribly. Just one little BlockHunt map lags the entire server to the point where simple tasks such as mining and fighting monsters are impossible, let alone working with more complex things such as plugins. To prove that it's Block Hunt's error, we tried disabling the one BH map that we created, and instantly, the lag went away...

**Comment by NovitiumCraft** [comment]
I am also having the same issue. Block Hunt is lagging my entire server with arenas. We need 1.8!

**Comment by tyiscool97** [comment]
YES YES YES! Please update!!! Lags our server out so badly! WE love this plugin! Everything is awesome!

**Comment by Sammayboy123** [comment]
Having the SAME issue, lags our server completely and make it impossible to do anything, PLEASE FIX!

**Comment by ModalInc** [comment]
I never had this issue with lag. I have actually updated a version of this plugin to 1.8 but it has afew alterations specific for my server so unsure if it should be released. Especially as i renamed foldernames and artifactId and such. Also made it work with Maven framework(meant it was easier to upgrade to newer versions of bukkit for me.)

E.G I removed Autoupdater and metrics as i didnt want it bukkit related anymore. Made it work with latest ProtocolLib, LibsDisguises and Vault. (Removed DisguiseCraft) and now uses Spigot/Bukkit 1.8. I added in a seperate value for SeekerDamage and added that to config.


But besides this. There shouldnt be any issues with lag if you use the latest Libdisguise and protocollib for 1.8. Can be found on md5's repo.

**Comment by eglbogle** [comment]
I'll try your suggestion but from what I could recall, updating ProtocolLib to 1.8 caused a few errors with some plugins. I'll try it, but if it doesn't work, then we need a 1.8 version for Block Hunt, which is the more preferable solution

**Comment by eglbogle** [comment]
Just a quick question. Where can I find a 1.8 update for Lib's Disguises? I already updated ProtocolLib, and everything works just fine.

**Comment by eglbogle** [comment]
I tried updating LibsDisguises. Not quite sure which of the two .jars I should download, but I tried both at one time, and both together, and it gave me this error:
Internal Exception: io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException: readerIndex(13) + length(12544) exceeds writerIndex(10509): UnpooledHeapByteBuf(ridx: 13, widx: 10509, cap: 10509/10509)

**Comment by xion87** [comment]
For me blockhunt work perfect use this one that is "unofficial" but working great and 0 lag:
http://jenkins.addstar.com.au/job/BlockHunt/

**Comment by tyiscool97** [comment]
thank you! This works perfectly! Really appreciated!

**Comment by xion87** [comment]
Np, you shoud thank @addstar for do this for us :)

**Comment by addstar** [comment]
You're welcome :grin:
My fork is actively used on my own server and will have active development as long as we're using it. Many performance fixes had to be made even for 1.7 and I will continue to improve my fork.
Not trying to steal the work or credit from @Steffion, it's a really great game, but it seems abandoned now (correct me if I'm wrong).

**Comment by SmallSansSerif** [comment]
Thanks!

**Comment by NoHoPeLess** [comment]
We all have this issues https://github.com/Steffion/BlockHunt/issues/324

**Comment by Minetastic08** [comment]
well i have manage to set up my arena but when the game starts everything starts to glitch and after about 10 seconds you get kicked and after 20 seconds later the whole server shutdown. why is this and how do i fix it???


Pleas help

**Comment by CoolLord22** [comment]
@addstar OMG I LOVE YOU SO MUCH THANK YOU THANK YOU THANK YOU!!! YOU ARE AMAZING!!!!

**Comment by Steffion** [comment]
The plugin has been updated and I hope you will try it out.
If you prefer addstar's version, be my guest.
