### ISSUE TITLE
1.7.9 spigot 

### ISSUE THREAD

**Issue by LegendaryMack** [Steffion/BlockHunt#322]
When Me an my friends try to join the block hunt on my server it won't start the game the signs dont change colors or anything and when you type to leave because it wont start it put you in the arena and says Internal Error occured while attempting to perform this command The Log is below 

Console	: [00:37:21 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Console	: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
Console	: org.bukkit.event.EventException
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:375) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:657) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:133) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
Console	: 	... 16 more
Console	: [00:37:27 INFO]: LegendaryMack issued server command: /bh leave
Console	: [00:37:30 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Console	: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
Console	: org.bukkit.event.EventException
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:375) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:657) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:133) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
Console	: 	... 16 more
Console	: [00:37:44 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Console	: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
Console	: org.bukkit.event.EventException
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:375) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:657) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:133) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
Console	: 	... 16 more
Console	: [00:38:11 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Console	: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
Console	: org.bukkit.event.EventException
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:375) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:657) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:133) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
Console	: 	... 16 more
Console	: [00:38:12 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Console	: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
Console	: org.bukkit.event.EventException
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:375) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:657) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:133) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
Console	: 	... 16 more
Console	: [00:38:13 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Console	: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
Console	: org.bukkit.event.EventException
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:375) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:657) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:133) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
Console	: 	... 16 more
Console	: [00:38:14 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Console	: Could not pass event PlayerInteractEvent to BlockHunt v0.2.0_BETA_B5
Console	: org.bukkit.event.EventException
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1543]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:375) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:657) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Listeners.OnPlayerInteractEvent.onPlayerInteractEvent(OnPlayerInteractEvent.java:133) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
Console	: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
Console	: 	... 16 more
Console	: [00:38:20 INFO]: LegendaryMack issued server command: /blockhunt
Console	: [00:38:24 INFO]: LegendaryMack issued server command: /bh
Console	: [00:38:32 INFO]: LegendaryMack issued server command: /bh help
Console	: [00:38:36 INFO]: LegendaryMack issued server command: /bh help 1
Console	: [00:38:45 INFO]: LegendaryMack issued server command: /bh j hide1
Console	: [00:38:45 ERROR]: null
Console	: org.bukkit.command.CommandException: Unhandled exception executing command 'bh' in plugin BlockHunt v0.2.0_BETA_B5
Console	: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1543]
Console	: 	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
Console	: 	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:1015) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:845) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1543]
Console	: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1543]
Console	: Caused by: java.lang.NullPointerException
Console	: 	at nl.Steffion.BlockHunt.Serializables.LocationSerializable.equals(LocationSerializable.java:31) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.ArenaHandler.playerJoinArena(ArenaHandler.java:104) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.Commands.CMDjoin.exectue(CMDjoin.java:21) ~[?:?]
Console	: 	at nl.Steffion.BlockHunt.BlockHunt.onCommand(BlockHunt.java:819) ~[?:?]
Console	: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1543]
Console	: 	... 13 more

**Comment by Steffion** [comment]
Try the latest version of the plugin.
If you still get errors, please report them again.
