### ISSUE TITLE
Blockhunt Lag

### ISSUE THREAD

**Issue by CDSnipez** [Steffion/BlockHunt#328]
Hello, I'm CDSnipez. I currently installed BlockHunt onto my server. Whenever I try to make an arena, it causes extreme lag on my server. I've tried checking the console for errors but there is nothing listed. The lag is like if I do a huge worldedit, though my server doesn't crash.

When I do /tps my server hits 9-10 TPS and it's dropped down to below 5 TPS as well. I'm completely lost at what's happening here. Possibly it could be the size of my arena? It's a pretty big arena. About i would say almost 100 blocks by 100 blocks. Its round though.

http://imgur.com/oGkXJE5

It also lasts throughout a restart as well.

Any help would be greatly appreciated :)

**Comment by JawsCHannelTv** [comment]
Same here CDSnipez, I don't believe it's the size. I just feel the plugin isn't functioning properly with the new 1.8. Hopefully we see a nice update soon. This is an amazing plugin :)

**Comment by NoodlyDoodly** [comment]
You can get a version of BlockHunt that is optimized to work with 1.8. I can't actually guarantee that there are no bugs, but it's worth a try (I've been able to use it on my own server).

**Comment by Steffion** [comment]
I said this in an issue on the fork of addstar:
>This is most likely like this because they way I coded it. I don't know what I was thinking while coding the plugin but I made it horrible. The only way to fix the timings (lag), which is critical, is to recode the whole plugin.

I am aware of the lag issues.

**Comment by JBluesword** [comment]
The reason for the lag is because their is a cpu leak where it will use 100% of your cpu of the server. This only happens to people using java 8. If you use java 7 you would be fine. Hope this help.
But overall this plugin is very buggy and still needs to be fixed.
