### ISSUE TITLE
Cant Use commands 

### ISSUE THREAD

**Issue by Ashplayer21** [Steffion/BlockHunt#332]
When i try to use /bh w i cant it dosnt let me do anything so i really hope you can fix this

**Comment by JBluesword** [comment]
Make sure that you have set the permission in your permission plugin or that you are opped.
Also what version of spigot and java are you using?

**Comment by Steffion** [comment]
This is most likely not a bug with BlockHunt.
Check your server configuration. If you need any more assistance, leave a comment.
