### ISSUE TITLE
Other players can't use Warp Signs!?!?

### ISSUE THREAD

**Issue by B00MERzY2K** [Steffion/BlockHunt#335]
I set up a BlockHunt arena but for some reason all of the non opped players can't click the "Join" signs to join a arena or click the "Leave" signs to leave an arena, and they can't even click on the "Shop" signs. Can you guys help me with this problem? I tried contacting my server providers but they said to come talk to the actual Developers of the Plugin as you guys would know more about it than they do. Please help guys, I am VERY desperate for help. Thanks guys!!! :)

**Comment by TheDigitalToaster** [comment]
Same here, worked for 1 time. Then only OPs where able to click it.

**Comment by Jnxd1** [comment]
I can not create any sign... :((( Dunno why! :/

**Comment by Steffion** [comment]
Make sure you give them the permission.
This is not a bug with BlockHunt.
