### ISSUE TITLE
Hunters Can't Use Bow's To Damage Hiders And Hiders Can't Use Sword

### ISSUE THREAD

**Issue by JBuscus** [Steffion/BlockHunt#336]
As in the title the Hunters Can't Harm Hiders With A Bow And Hiders Can't Use There Wooden Sword
Any Idea's?

Just so you know Hunters Can Still Use There Sword To Attack

Edit: Using Newest 1.8.3 build

**Comment by Stampede2011** [comment]
I have the same problem! I cant find the fix D:

**Comment by DevilBabyZZY** [comment]
I have the same problem too.And I use the 1.8.7 build 7-2.

**Comment by Steffion** [comment]
Should be fixed with #366 .
If you still have troubles with it, leave a comment.
