### ISSUE TITLE
Players were able to join but suddenly it doesnt work anymore.

### ISSUE THREAD

**Issue by TheDigitalToaster** [Steffion/BlockHunt#337]
So they where able to join, but then suddenly clicking the shop sign and join sign doesn't do anything anymore. not even a "You don't have permission" message. I reinstalled the plugin remode the arena, everything. Can't find the problem.

**Comment by TheDigitalToaster** [comment]
Edit: only OPs could join.

**Comment by RandomPanda30** [comment]
@TheDigitalToaster Irrelevant issue now as BlockHunt is currently being recoded completely.
