### ISSUE TITLE
Seekers get tped to hiders spawn when even turning character.

### ISSUE THREAD

**Issue by TheDigitalToaster** [Steffion/BlockHunt#338]
So i made a seekers lobby where they wait outside the arena. But even when they just turn their head they get spawned on the hider location.

**Comment by TheDigitalToaster** [comment]
Making the seeker wait location inside the arena fixed it :)

**Comment by Steffion** [comment]
Congratulations, you found the easter egg!
:tada:

**Comment by TheDigitalToaster** [comment]
@Steffion Hey man, i'm sorry.
Just one more question. I have an economy plugin. Can I add custom command for when a player wins he gets coins for the economy?
Thanks in advance.
