### ISSUE TITLE
Seekers do not last in the seeker's warp for more than half a second

### ISSUE THREAD

**Issue by NoodlyDoodly** [Steffion/BlockHunt#340]
This issue occurs on both my Spigot 1.8 server and my Bukkit 1.7 server. Put simply, when a game of hide-and-seek starts, whoever is the seeker goes to the seeker warp, but barely even has time to turn around, because almost instantly they are teleported to where the hiders warp is. 20 seconds later, which is when they should teleport out of the seeker's warp, they are teleported to where the hiders should start for a second time. What kind of mistake could I have made to cause this, or is this a current bug in BlockHunt?

By the way, I have already checked that both warps aren't in the same place. There are no errors generated anywhere when this occurs.

**Comment by Steffion** [comment]
Are you sure both warps are INSIDE the cuboid you selected the arena with?
Else that's your problem.
