### ISSUE TITLE
Seeker damage / Seeker spawn / TeleportOut

### ISSUE THREAD

**Issue by GRRRillaNinja** [Steffion/BlockHunt#348]
Using v0.2.1 of your plugin and Spigot 1.8.3

As mentioned in previous tickets, seekers cant damage with the bow, and hiders can't hit seeker with their swords.

Seeker also spawns with hiders immediately without waiting for the 20 second delay.

And also, when the match is over, players are not teleported to their previous location they were before joining the arena.

**Comment by blake0201** [comment]
You Need To Set SpawnProtection To 0 in server.properties that should fix the pvp problom

**Comment by GRRRillaNinja** [comment]
I already have it set at 0

**Comment by Steffion** [comment]
Your issue should be fixed with #371.
