### ISSUE TITLE
One delema... 

### ISSUE THREAD

**Issue by Curdic** [Steffion/BlockHunt#349]
http://dev.bukkit.org/bukkit-plugins/libs-disguises/ (Lib's Disguises) wont actually work anymore, seeing as it has been deleted... making this entire plugin null.

**Comment by niemoiscool** [comment]
Lib's Disguises moved to here https://www.spigotmc.org/resources/libs-disguises.81/

**Comment by Curdic** [comment]
Thank you very much for this information!
