### ISSUE TITLE
Players cant turn into blocks

### ISSUE THREAD

**Issue by DreamingGamer1** [Steffion/BlockHunt#352]
I am making this game on my server with my friends but when me and my friend play the game, they don't turn into the block they chose. Can anyone help? Also i do have protocollib and libsdisguises.

**Comment by Jnxd1** [comment]
read careful what it says on the page you have to have to proper version to make it work.On my serv it works just fine

**Comment by DreamingGamer1** [comment]
I'm using Apex minecraft server hosting for my server and there is only one version for protocolLib and Libsdisguises. Thanks for your response.

**Comment by Jnxd1** [comment]
Block Hunt - http://dev.bukkit.org/bukkit-plugins/blockhunt/
ProtocolLib - http://dev.bukkit.org/bukkit-plugins/protocollib/
Lib's Disguises - https://www.spigotmc.org/resources/libs-disguises.81/
U/w , read which version of Lib's Disguises suites ur server.
