### ISSUE TITLE
Seeker Spawn Not Working

### ISSUE THREAD

**Issue by bittz** [Steffion/BlockHunt#356]
Every time I start a game, the seeker teleports to the seeker spawn, than teleports them to the hider spawn before the "grace period" or "respawn" time is up.

**Comment by JBluesword** [comment]
They way it works you put the seekers in a dark place or jail place where they can't see anything. The plugin will then teleport the seekers into the game. The spawn you set for seekers it just where you put them to hide and can't see anything. Like for mine i put my seekers in a dark room

**Comment by vanwiththeplan** [comment]
when i use it it just teleports them into the game even whhen i set a seeker way point

**Comment by Steffion** [comment]
Put the seeker spawn inside the selected arena cuboid. Otherwise they will be teleported out  due to 'leaving' the arena area. This is not a bug, it is just confusing.
