### ISSUE TITLE
Signs put users in 2 times

### ISSUE THREAD

**Issue by doglover129** [Steffion/BlockHunt#357]
When using a sign, a player is put into the game twice. I am running on a Spigot server. Could this be the issue? Thanks!

**Comment by MrFrostmaul** [comment]
BTW, this plugin is no longer being developed/updated :(

**Comment by JBluesword** [comment]
I was suppose to update this plugin to 1.8.8 spigot but sadly i started to fall behind in school. I will also not be able to update it. Sorry

**Comment by Steffion** [comment]
Is this still happening?
