### ISSUE TITLE
THE WHOLE SERVER LAGS WHEN I TRY AND SET AN ARENA UP

### ISSUE THREAD

**Issue by Minetastic08** [Steffion/BlockHunt#359]
hi there.
i have stumbled across your plugin and find it to be rely good. but when i try and set it up on my server everything starts to lag. i manage to set up 1 map witch took me 30 minutes.
can you pleas fix this ASAP

thanks Minetastic

**Comment by JBluesword** [comment]
It is because of java new update the plugin cant handle it and will crash ur server. Remove the plugin right away or it might corrupt some stuff. Or downgrade on java to java 7

**Comment by JBluesword** [comment]
Your tps will drop to 3. Their is a cpu leak usage it will use 100% of the server cpu

**Comment by RandomPanda30** [comment]
CPU leak usage - I'm done lol. This plugin isn't being worked on anymore. Maybe it will eventually

**Comment by JBluesword** [comment]
I was suppose to work on this plugin to make it 1.8.8 compatible but sadly school interfered. In the future I plan on recreating the whole entire plugin. To make it work with 1.9

**Comment by Minetastic08** [comment]
well if you are planing to may i know when as i realy want this plugin on my server but you are the only one who is planing to make a 1.8/1.9
if you are can you pleas make it in 2016 or bevore it ends

Pleas you are my only hope

also make it so they can become a mob like sheep and pigs


thanks Minetastic

**Comment by RandomPanda30** [comment]
K
