### ISSUE TITLE
Seeker & Hider Damage Stuff...

### ISSUE THREAD

**Issue by CoolLord22** [Steffion/BlockHunt#362]
Just a question, I've seen this issue floating around and am not sure what to do about it. Seekers cannot use their bows to damage Hiders, and Hiders cannot attack Seekers. Here is my config for an arena called Castaway. Thanks for any help!

Castaway:
  ==: BlockHuntArena
  seekersCanHurtSeekers: true
  hidersCanHurtSeekers: true
  hidersCanHurtHiders: true
  seekersTakeFallDamage: true
  hidersTakeFallDamage: true
  maxPlayers: 15
  hidersWinCommands: []
  timeInLobbyUntilStart: 50
  minPlayers: 2
  timeUntilHidersSword: 60
  spawnWarp:
    ==: BlockHuntLocation
    p: 90.0
    a: 270.3591
    w: Blockhunt
    x: -1.47250588969198
    y: 5.0
    z: 8.488718280669769
  allowedCommands: []
  arenaName: Castaway
  amountSeekersOnStart: 1
  pos1:
    ==: BlockHuntLocation
    w: Blockhunt
    x: -223.0
    y: 214.0
    z: -411.0
  pos2:
    ==: BlockHuntLocation
    w: Blockhunt
    x: -104.0
    y: 160.0
    z: -515.0
  waitingTimeSeeker: 20
  seekersTokenWin: 10
  lobbyWarp:
    ==: BlockHuntLocation
    p: 6.671223
    a: -89.08293
    w: Blockhunt
    x: 4.317987157856248
    y: 4.0
    z: 8.388547837144266
  seekersWinCommands: []
  killTokens: 8
  gameTime: 600
  disguiseBlocks:
  - ==: org.bukkit.inventory.ItemStack
    type: MELON_BLOCK
  - ==: org.bukkit.inventory.ItemStack
    type: PUMPKIN
  - ==: org.bukkit.inventory.ItemStack
    type: MOSSY_COBBLESTONE
  - ==: org.bukkit.inventory.ItemStack
    type: GRAVEL
  - ==: org.bukkit.inventory.ItemStack
    type: BRICK
  - ==: org.bukkit.inventory.ItemStack
    type: OBSIDIAN
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
  - ==: org.bukkit.inventory.ItemStack
    type: BOOKSHELF
  - ==: org.bukkit.inventory.ItemStack
    type: WORKBENCH
  - ==: org.bukkit.inventory.ItemStack
    type: FURNACE
  - ==: org.bukkit.inventory.ItemStack
    type: JUKEBOX
  - ==: org.bukkit.inventory.ItemStack
    type: NOTE_BLOCK
  - ==: org.bukkit.inventory.ItemStack
    type: BEACON
  - ==: org.bukkit.inventory.ItemStack
    type: TNT
  hidersWarp:
    ==: BlockHuntLocation
    p: 3.4485016
    a: 89.65946
    w: Blockhunt
    x: -109.74940977687022
    y: 173.5
    z: -462.6678616789377
  blockAnnouncerTime: 90
  seekersWarp:
    ==: BlockHuntLocation
    p: 2.4127283
    a: 90.46511
    w: Blockhunt
    x: -109.60939764998456
    y: 171.0
    z: -462.4816317276817
  hidersTokenWin: 50

**Comment by Steffion** [comment]
Is this still happening?
If so, please post a list of your plugins too.

**Comment by CoolLord22** [comment]
Yeah but the issue is strange, the config part gets rid of the 
"seekersCanHurtSeekers: true
hidersCanHurtSeekers: true
hidersCanHurtHiders: true
seekersTakeFallDamage: true
hidersTakeFallDamage: true"
Part in every time the plugin loads.

**Comment by CoolLord22** [comment]
(Take out the "in" don't know why I typed that)

**Comment by Steffion** [comment]
My version of the plugin does not even use those configurations. Are you sure this problem is with my version or the one from addstar?

**Comment by CoolLord22** [comment]
Derp xD where can I download your version? (Is it updated for 1.8?)

**Comment by Steffion** [comment]
You can find the latest version here http://jenkins.steffion.com/job/BlockHunt/ for MC 1.9

**Comment by CoolLord22** [comment]
Is it for 1.8 as well? (I'm on my phone in the car so I can't download atm xD)

**Comment by Steffion** [comment]
I am not sure if it will run on 1.8, but you can try.

**Comment by CoolLord22** [comment]
Alrighty. Thanks!

**Comment by RandomPanda30** [comment]
Closing as solved for now. Create a new issue if any problems occur

**Comment by CoolLord22** [comment]
Plugin does not work with version 1.8.9. Thanks anyways I guess...

**Comment by Steffion** [comment]
I would suggest to update your MC version.
I don't see why you want to hold back any longer. Most plugins are updated now anyway.

**Comment by CoolLord22** [comment]
I hate 1.9 xD and most, but not all.

**Comment by Steffion** [comment]
You can compile the code for 1.8 and fix the bugs.
As for now we do not support 1.8. Sorry.

**Comment by Steffion** [comment]
You can try this, but it is not guaranteed to work.
http://jenkins.steffion.com/job/BlockHunt-1.8/

**Comment by CoolLord22** [comment]
Alrighty. Thank you! I'll try it when I get home.

**Comment by CoolLord22** [comment]
AHH IT WORKS!!! THANK YOU SO MUCH!!!!!!!!!!!!!
