### ISSUE TITLE
Crash after game start

### ISSUE THREAD

**Issue by EnDoSiA** [Steffion/BlockHunt#365]
I have a problem after setting arena players to join in the lobby all works but when it is about to start spawns players and the game all fall. You do not know where is the problem?

In Console is only: ERROR]: java.lang.ClassCastException: net.minecraft.server.v1_9_R1.BlockPosition cannot be cast to com.google.common.base.Optional

and minecraft error:Internal Exceeption io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(21) + length(1) exceeds writerIndex(21) UnpooledHeapByteBuf(ridx 21,widx 21, cao:21)

The latest version:R: BlockHunt v0.2.0 for 1.9
Server version:CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

I dont know problem is with BlockHunt or spigot

**Comment by kamikazifroasty** [comment]
having the same issue. all players are kicked from server at game start. same error in console aswell

**Comment by Steffion** [comment]
Does it say anything more in the console? It would help finding and fixing the problem.

**Comment by EnDoSiA** [comment]
No more errors, only this

**Comment by EnDoSiA** [comment]
I try start a game and i got this ERROR: 

ERROR]: java.lang.ClassCastException: net.minecraft.server.v1_9_R1.BlockPosition cannot be cast to com.google.common.base.Optional

> [21:59:12 ERROR]: java.lang.ClassCastException: net.minecraft.server.v1_9_R1.BlockPosition cannot be cast to com.google.common.base.Optional
> [21:59:12 INFO]: java.lang.reflect.InvocationTargetException
> [21:59:12 INFO]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:59:12 INFO]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [21:59:12 INFO]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:59:12 INFO]: at java.lang.reflect.Method.invoke(Method.java:498)
> [21:59:12 INFO]: at me.libraryaddict.disguise.utilities.DisguiseUtilities.refreshTrackers(DisguiseUtilities.java:731)
> [21:59:12 INFO]: at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:460)
> [21:59:12 INFO]: at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:373)
> [21:59:12 INFO]: at be.isach.ultracosmetics.CustomPlayer.clear(CustomPlayer.java:331)
> [21:59:12 INFO]: at be.isach.ultracosmetics.run.InvalidWorldManager.run(InvalidWorldManager.java:21)
> [21:59:12 INFO]: at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
> [21:59:12 INFO]: at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> [21:59:12 INFO]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [21:59:12 INFO]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [21:59:12 INFO]: at java.lang.Thread.run(Thread.java:745)
> [21:59:12 INFO]: Caused by: java.lang.IllegalStateException: Asynchronous player tracker clear!
> [21:59:12 INFO]: at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
> [21:59:12 INFO]: at net.minecraft.server.v1_9_R1.EntityTrackerEntry.clear(EntityTrackerEntry.java:562)
> [21:59:12 INFO]: ... 14 more
> [21:59:12 INFO]: EndoCreep lost connection: Disconnected
> [21:59:12 INFO]: [-] EndoCreep

**Comment by Steffion** [comment]
Are you sure the dependencies are up to date? (LibsDisguises and ProtocolLib)

**Comment by EnDoSiA** [comment]
I using latest versions 
LibsDisguises - 9.0.3
ProtocolLib - v4.0.0

**Comment by EnDoSiA** [comment]
If you need I can show you the problem directly to the server (IP messenger in mozme pm and will be agreed on)

**Comment by Steffion** [comment]
I already tried to join the server earlier, but my country is banned on your server.
If you could whitelist me somehow I will try to join again when I have the time.

On-topic: I can't find the problem at the moment but I will keep searching. If you find some additional information, post it here.

**Comment by EnDoSiA** [comment]
If you have a time, i waiting on server now

**Comment by EnDoSiA** [comment]
All right, I arrived at the problem and it starts working properly. Problem I do not know where he was. Spigot I updated to the latest version 1.9.2 and ProtocolLIB the latest version of the build # 271 and then the game went well and afterwards they were unaware converted player on the block, this problem was the LibDisquise and UltraCosmetic plugins that use are actually about transformation and somehow together did not understand so after turning off UltraCosmetic plugin now everything is going as it should without any problem. Thank you for an amazing plugin :)

Can you please add an option to set up custom commands for the reward?

Thank you, Have a nice rest of the day
