### ISSUE TITLE
Allow PvP even when other plugins block it

### ISSUE THREAD

**Issue by kamikazifroasty** [Steffion/BlockHunt#366]
please add an option to allow players to be "found" by just hitting them, or right clicking the player. Our server has a Team / clan pvp protection that is getting in the way of players being able to be discovered / tp'd to the seeker spawn as they cant hurt each other. thank you

**Comment by Steffion** [comment]
I think it is a good idea to have a way to play the game while another plugin like Factions or WorldGuard is preventing PvP.

Thanks, will be looked at.

**Comment by Steffion** [comment]
This is fixed in the latest dev snapshot and will be added to the upcoming release.
