### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by Krasnoid** [Steffion/BlockHunt#368]
I have heard that I should use Java 7 for this plugin because the new java uses 100% of my server cpu but it does not to me( for some reason). The problem with me is that Java 7 is no more available but only available for people who donated for oracle. I am kind of sure it is about Java because when I start Blockhunt with my friends it always kicks everybody out and tells them a strange piece of text. If you need any more info tell me please.

 I am using Java 8 77

**Comment by RandomPanda30** [comment]
Java 7 is not needed. The reason we say use Java 7 is because it's been compiled against that version of Java.

The best thing about Java though, is that it's backwards compatible so it should work just find on your Java 8 server.

**Comment by RandomPanda30** [comment]
Reopening a second, would you mind explaining what this bug is?

**Comment by Krasnoid** [comment]
Well, when I and my friend join a game just before we get put into the game we get kicked and we get this message :
![minecraft 1 9 2 16_04_2016 18_01_53](https://cloud.githubusercontent.com/assets/18498745/14589272/f4db4b22-04d5-11e6-9bbe-b73238682915.png)

We never get to play the game at all

**Comment by Steffion** [comment]
This should be fixed if you update your plugins.
Read #375 .
