### ISSUE TITLE
Plugin wont show up in plugins list

### ISSUE THREAD

**Issue by ClearlyRubix** [Steffion/BlockHunt#370]
I have all the necessary plugins installed and the BlockHunt plugin still wont show up.
I am running a 1.9 server and it wont show up.

**Comment by Steffion** [comment]
I don't understand your problem.

If you do /plugins in-game does it appear there? Have you restarted the server? Do you have the required dependencies installed?

**Comment by ClearlyRubix** [comment]
I have the required plugins installed and they show up in the /plugins but blockhunt doesn't show up

**Comment by Steffion** [comment]
Does it show any errors in the console?

**Comment by Steffion** [comment]
If this error still persists, leave another comment.
Closing for now.
