### ISSUE TITLE
Hiders problem

### ISSUE THREAD

**Issue by ZeTsUnAmY** [Steffion/BlockHunt#372]
Hello,
I've got a strange problem.
We can see the "path" of the hiders.
For exemple : A hider walk and hide as a stair, we can see stairs along his path...
Any idea ?
I'm on bukkit 1.9.
Thanks a lot !

**Comment by Steffion** [comment]
Do you mean that the stair blocks stay behind?
What versions are you running of the dependencies and BlockHunt self?
Could you upload a screenshot?

**Comment by ZeTsUnAmY** [comment]
Hello,
I use ProtocolLib 3.7.0 Beta and LibsDisguise 9.0.3
Here is a "screenshot"... sorry it was one of my friend who did this ^^
http://hpics.li/78acf9e

**Comment by Steffion** [comment]
Could you tell me what plugins you are running?

**Comment by ZeTsUnAmY** [comment]
Here is the list...
http://hpics.li/dcde110

**Comment by Steffion** [comment]
Do you mind leaving your server IP behind so I can join and have a look myself?
I can't seem to find the problem at this point.

**Comment by ZeTsUnAmY** [comment]
Hello, I send it on steffion@icloud.com ?

**Comment by Steffion** [comment]
Sure or leave it here, I don't mind.
