### ISSUE TITLE
Issue with "%killer%" variable in 1.8 version

### ISSUE THREAD

**Issue by CoolLord22** [Steffion/BlockHunt#373]
Hey Steffion (or whoever sees this) there's just a slight issue. Instead of showing the killer who killed the hider, it just shows [BlockHunt] Hider <TheirName> was killed by %killer%! Like it doesn't show the name of the killer.

**Comment by Steffion** [comment]
Your messages.yml values are incorrect.

These are the default values:
>  ingameHiderDied: '%TAG%NHider %A%playername%%N died! %A%left%%N hider(s) remain...'
  ingameSeekerDied: '%TAG%NSeeker %A%playername%%N died! He will respawn in %A%secs%%N
    seconds!'

Thanks for reporting.
