### ISSUE TITLE
wand

### ISSUE THREAD

**Issue by anemul** [Steffion/BlockHunt#374]
When setting up my arena with the latest version 021 , /blockhunt wand did not give me wand , just said that command was not found . I used world edit tool and it seemed to wrk all though it didn't give me any boundary set notices .

**Comment by Steffion** [comment]
I removed the wand because it was causing too many problems.
You no longer have to set boundaries.
If you want to enable the wand anyway, you can edit the config.yml and find the 'wandEnabled' setting.
