### ISSUE TITLE
Error when game starts, players get kicked Spigot 1.9.2

### ISSUE THREAD

**Issue by Dennis000903** [Steffion/BlockHunt#375]
Whenever I joined an lobby and the game starts, instead of teleporting the players into an arena, players get kicked from the game. This happens every time, you try to play. When you get kicked, it puts you out this error:

http://up.picr.de/25393777po.jpg

Using spigot 1.9.2

**Comment by Steffion** [comment]
Could you list your plugins and give me the error from the console?

**Comment by Dennis000903** [comment]
@Steffion No problem. My **plugins **are:

- Bedwars reloaded
- Blockhunt
- Chestcommands Gui
- citizens 2.0.17 snapshot
- commandNPC
- customjoinitems
- holografic displays
- iconomy recreation
- joincommands 4.0
- libsdisguises
- multiinv
- multiworld
- nocheatplus
- paintball pure war
- permissionsex 1.23.4
- protocollib
- scoreboardstats
- signcolors
- simplecrates
- spawnjoin v5.0
- tuxtwolib
- vault
- worldedit
- worldguard


**The error:**


[12:17:51] [Netty Epoll Server IO #0/ERROR]: java.lang.ClassCastException: net.minecraft.server.v1_9_R1.BlockPosition cannot be cast to com.google.common.base.Optional

This line appears as often as players are getting kicked... No more errors, this is the only one from the console.

**Comment by Steffion** [comment]
Could you try to update the dependencies? LibsDisgusies & ProtocolLib

**Comment by Dennis000903** [comment]
Just updated LibsDisguises and ProtocolLib to latest stable versions (Both are now official supporting 1.9). Still the same error.

**Comment by Steffion** [comment]
Is your spigot up to date to the latest build? Try a dev build of the dependencies. I really can't find a problem with the plugin.
Besides, it works fine for me.

**Comment by Dennis000903** [comment]
It works with latest dev builds now, no error. But instead of that, the Hider gets invisible and gets no damage. I downloaded the latest spigot on last friday with buildtools, it should be relatively new. Which versions are you using?

**Comment by Steffion** [comment]
The visibility and invincibility could be a conflicting plugin like WorldGuard, check that first.
I am using the latest versions of everything.

**Comment by Dennis000903** [comment]
Worldguard isn't protecting this world, where my blockhunt maps are in.

**Comment by Steffion** [comment]
The plugin works for me without any other plugin. So it must be another plugin of yours conflicting with it. I really can't help with that.
