### ISSUE TITLE
game start

### ISSUE THREAD

**Issue by Jacksharkben** [Steffion/BlockHunt#376]
when they join the lobby it works but when the game starts they get kicked with a error thing

**Comment by Steffion** [comment]
As reported earlier today #375 , you have to update your Bukkit/Spigot version BlockHunt version to 0.2.1 and the dependencies, LibsDisguises and ProtocolLib. It should work then.

**Comment by Jacksharkben** [comment]
set the server to 1.9.2 seeing if that will fix it.

**Comment by Jacksharkben** [comment]
nope i get this
![error](https://cloud.githubusercontent.com/assets/19135398/14945172/57f1252e-0fd0-11e6-9636-5cea105c7a94.PNG)

**Comment by Jacksharkben** [comment]
@Steffion I did all of that and still get the error.

**Comment by Steffion** [comment]
Are you using 3.7.0-BETA of ProtocolLib?

**Comment by Jacksharkben** [comment]
I downloaded the 3.7.0-BETA I am now seeing if it worked. Also do I want to upgrade to the 4.0 when it comes out?

**Comment by Steffion** [comment]
Always try to run the latest version of everything, this will prevent issues. I can't help you more, so I hope that it works now.
