### ISSUE TITLE
kicked when the game starts

### ISSUE THREAD

**Issue by AlexNova1555** [Steffion/BlockHunt#378]
hey man i have a bug that when the game start so its kick all the players with strange kick msg
and some error at the console here have a look
Kick :http://prnt.sc/azw156
Error: http://pastebin.com/g3Au6Caj
Spigot version http://prnt.sc/azq6l5
ProtocoLib: 3.7.0-BETA
libsdisguises: 9.0.3
BlockHunt 0.2.1

**Comment by Steffion** [comment]
Try updating your Spigot version.
Other users had this too and got it fixed by updating their plugins/server.
#375

**Comment by AlexNova1555** [comment]
sure i will update you if its still not working :D

**Comment by AlexNova1555** [comment]
Update:
i have updated every single plugin that i had still didn't help me same error
i have updated the spigot version still didn't help me same error
i have deleted every single plugin to check if its bug with other plugin still didn't help me same error
i don't know )":

**Comment by Steffion** [comment]
The plugin is working fine for most people so I really can't help you on this anymore.
Good luck.

**Comment by AlexNova1555** [comment]
can you please give me the protocollib and LibsDisguises that you are using ?
because i found out its because the LibsDisguises

**Comment by Steffion** [comment]
It works with 9.0.3 of libsdisguises.

**Comment by AlexNova1555** [comment]
alright i have fix it ;D
i was just need to download devbuild of protocolLib :dancers:

**Comment by Steffion** [comment]
Great. Have fun using my plugin ;)
