### ISSUE TITLE
can not find plugin.

### ISSUE THREAD

**Issue by Jacksharkben** [Steffion/BlockHunt#379]
my server cant find the plugins that are needed for it to work
and i do have them

**Comment by Steffion** [comment]
Have you restarted the server?

**Comment by Jacksharkben** [comment]
Yes

**Comment by Jacksharkben** [comment]
I also have plugman and I had it reload the server.

**Comment by Steffion** [comment]
Well this is not an issue with my plugin. You have to check it on your side.
Make sure both dependencies are installed and you have updated everything including the server software.
