### ISSUE TITLE
Help!! We Joined But it is also 0/8 player 0/8 the same..

### ISSUE THREAD

**Issue by TongLyKung** [Steffion/BlockHunt#380]
Help!! We Joined But it is also 0/8 player 0/8 the same..
A1 Join 0/8
B2 Join 0/8
This is 1/8,2/8  the same.. 0/8
craft BlockHunt 1.7.2
Help
form thailand

**Comment by Steffion** [comment]
I am sorry but I cannot understand your question/issue at all.
Please try again with some decent english language.

If you have any problems, try to update all dependencies and the plugin itself.
The plugin has been tested and works completely fine with the latest software.
