### ISSUE TITLE
Health set throws IllegalArgumentException

### ISSUE THREAD

**Issue by jomjonejame** [Steffion/BlockHunt#381]
Spigot 1.8.8
BlockHunt v0.2.1-MC1.8.8

Game over. But the players are not Teleport to spawn. To use the command [ /bh leave ] to leave the game.

and BlockHunt v0.2.1-MC1.8.8 No command  [ /bh wand ]

URL : http://pastebin.com/AUU0p8Jz

**Comment by Steffion** [comment]
Thank you for reporting this bug, I will have a look at it as soon as possible.

For the wand issue, I removed the wand system because it was giving to many problems. It is no longer needed to set boundaries of an arena. If you want to enable it anyway go to the config file and change wandEnabled.

**Comment by jomjonejame** [comment]
I wait for updates

**Comment by Steffion** [comment]
Should be fixed, please try the latest build.

**Comment by jomjonejame** [comment]
Please download link

**Comment by Steffion** [comment]
http://jenkins.steffion.com/job/BlockHunt-1.8/
