### ISSUE TITLE
Error  while joining

### ISSUE THREAD

**Issue by InfamousYT** [Steffion/BlockHunt#383]
Hi, as soon as the game of blockhunt starts it disconnects players with message: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(1) exceeds writerIndex(24): UnpooledHeapByteBuf(ridx: 24, widx: 24, cap: 24)

Version 2.22

Game Version: 1.9.x

**Comment by Steffion** [comment]
This is not a bug with the plugin. Make sure you are running the latest version of ProtocolLib.
