### ISSUE TITLE
这有个bug

### ISSUE THREAD

**Issue by MlgmXyysd** [Steffion/BlockHunt#393]
使用1.9.2版本的Spigot
0.2.1和0.3.0的BlockHunt
LibD是9.0.9版本的
其中0.3.0的BH提示LibD未安装
0.2.1配置好后，开始游戏倒计时结束，玩家一直在大厅里，也没有变身方块，只有寻找者到了地图里

**Comment by Steffion** [comment]
You will have to translate this to English.
