### ISSUE TITLE
Hiders Get Stuck in BlockHunt Lobby

### ISSUE THREAD

**Issue by Seamonkeyking** [Steffion/BlockHunt#394]
Hi so I have BlockHunt v0.2.1, LibsDisguises v9.0.9, and ProtocolLib.  They are all the most updated versions.  For some reason whenever I try a blockhunt game the Seekers are teleported to their warp but the Hiders get stuck at the blockhunt lobby and cant move at all.  I am not sure if this is a reoccurring error, but I think it should be looked into.  Please help ASAP because I would like to get my server up sooner than later.  Thank you so much!

**Comment by Steffion** [comment]
Are you using the wand tool? If so, make sure the y positions aren't on the same level.

**Comment by Seamonkeyking** [comment]
Hey thank you for responding so quickly.  Yes I am using the wand tool, and by wand tool I am assuming the stick it gives you.... The y positions are not on the same level as well.  I don't know if this will help at all but here is a paste bin of my arenas config if you wanted to check it out and see if anything looked weird about it.   Also if you want I could always give you my server ip so that you can see the problem i am talking about.

http://pastebin.com/jjyQS4eW
