### ISSUE TITLE
Probleme création map

### ISSUE THREAD

**Issue by DJClement50** [Steffion/BlockHunt#396]
Il n'y a pas de moyen pour créer la zone

**Comment by DJClement50** [comment]
Why have not you responded to my problem before closing ?

**Comment by Steffion** [comment]
Only English tickets will get help.
If it is an issue with the plugin, I most likely can not help you anyhow.

**Comment by DJClement50** [comment]
Ok, my problem comes right plugin, because I did not create zone for the game told me his command unknown.

**Comment by Steffion** [comment]
If this is about the wand command check: #374

**Comment by DJClement50** [comment]
I had not paid attention

Thank you for your response.
