### ISSUE TITLE
Error that the warp is not installed

### ISSUE THREAD

**Issue by FrukTik** [Steffion/BlockHunt#407]
Hi. The arena was on time, installed all the warp, everything works. But after rebooting the server gives an error that the warp is not installed. In the config all the settings are unchanged. What could be the reason?
BlockHunt version 0.3.0-SNAPSHOT-
Paper version git-Paper-1313 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Steffion** [comment]
I am afraid I cannot help you with this issue. I am no longer into Minecraft plugin development, feel free to try the fork of my plugin here: https://github.com/AddstarMC/BlockHunt
