### ISSUE TITLE
Support for DisguiseCraft and Lib's Disguises.

### ISSUE THREAD

**Issue by CapnDuckface** [Steffion/BlockHunt#54]
Please provide compatibility to both DisguiseCraft and Lib's Disguises.

Lib's DisguiseCraft is not only terribly unfriendly to player commands outside of BlockHunt, but granting as many permissions to individual settings using Lib's DC is next to impossible for those of us that actually use disguise plugins for more than just gaming purposes.

Burning mobs, different mob variants, etc. are not explained in any way with Lib's and/or  are not supported. This actually limits it significantly compared to regular DC.

**Comment by Steffion** [comment]
This is not going to be added, sorry.
